name: search

ports:
  - port: 8082
    targetPort: 8082
 
container:
  command: /go/bin/search
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-search
  ports:
  - containerPort: 8082

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "search_server_cert.pem"
      name: "server_cert.pem"
    - filename: "search_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
