name: profile

ports:
  - port: 8081
    targetPort: 8081
 
container:
  command: /go/bin/geo
  image: deathstarbench/hotel-reservation
  name: hotel-reserv-profile
  ports:
  - containerPort: 8081

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
