name: profile

ports:
  - port: 8081
    targetPort: 8081
 
container:
  command: /go/bin/profile
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-profile
  ports:
  - containerPort: 8081

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "profile_server_cert.pem"
      name: "server_cert.pem"
    - filename: "profile_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
