name: reservation

ports:
  - port: 8087
    targetPort: 8087
 
container:
  command: /go/bin/reservation
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-reservation
  ports:
  - containerPort: 8087

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "reservation_server_cert.pem"
      name: "server_cert.pem"
    - filename: "reservation_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
