name: user

ports:
  - port: 8086
    targetPort: 8086
 
container:
  command: /go/bin/user
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-user
  ports:
  - containerPort: 8086

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "user_server_cert.pem"
      name: "server_cert.pem"
    - filename: "user_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
