version: "3.8"

x-hotel-service: &hotel-service
  image: ${HOTEL_RESERVATION_IMAGE}
  build:
    context: .
  environment:
    - TLS
    - GC
    - JAEGER_SAMPLE_RATIO
    - LOG_LEVEL
  configs:
    - source: server_config
      target: /config.json
  depends_on:
    - consul
  restart: always
  deploy:
    replicas: 1
    restart_policy:
      condition: any

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend:
    <<: *hotel-service
    entrypoint: frontend
    ports:
      - "5000:5000"

  profile:
    <<: *hotel-service
    entrypoint: profile
    depends_on:
      - mongodb-profile
      - memcached-profile

  search:
    <<: *hotel-service
    entrypoint: search

  geo:
    <<: *hotel-service
    entrypoint: geo
    depends_on:
      - mongodb-geo

  rate:
    <<: *hotel-service
    entrypoint: rate
    depends_on:
      - mongodb-rate
      - memcached-rate

  review:
    <<: *hotel-service
    entrypoint: review
    image: ${HOTEL_RESERVATION_IMAGE}-review
    container_name: 'hotel_reserv_review'
    depends_on:
      - mongodb-review
      - memcached-review

  attractions:
    <<: *hotel-service
    entrypoint: attractions
    image: ${HOTEL_RESERVATION_IMAGE}-attractions
    container_name: 'hotel_reserv_attractions'
    depends_on:
      - mongodb-attractions

  recommendation:
    <<: *hotel-service
    entrypoint: recommendation
    depends_on:
      - mongodb-recommendation

  user:
    <<: *hotel-service
    entrypoint: user
    depends_on:
      - mongodb-user

  reservation:
    <<: *hotel-service
    entrypoint: reservation
    depends_on:
      - mongodb-reservation
      - memcached-reserve

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-rate:
    image: memcached:latest
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-review:
    image: memcached:latest
    container_name: 'hotel_reserv_review_mmc'
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always

  memcached-profile:
    image: memcached:latest
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-reserve:
    image: memcached:latest
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-geo:
    image: mongo:5.0
    hostname: geo-db
    volumes:
      - geo:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-profile:
    image: mongo:5.0
    hostname: profile-db
    volumes:
      - profile:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-rate:
    image: mongo:5.0
    hostname: rate-db
    volumes:
      - rate:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-review:
    image: mongo:5.0
    hostname: review-db
    volumes:
      - review:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-attractions:
    image: mongo:5.0
    hostname: attractions-db
    volumes:
      - attractions:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-recommendation:
    image: mongo:5.0
    hostname: recommendation-db
    volumes:
      - recommendation:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-reservation:
    image: mongo:5.0
    hostname: reservation-db
    volumes:
      - reservation:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-user:
    image: mongo:5.0
    hostname: user-db
    volumes:
      - user:/data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user:
  review:
  attractions:

configs:
  server_config:
    file: ./config.json
