name: recommendation

ports:
  - port: 8085
    targetPort: 8085
 
container:
  command: /go/bin/recommendation
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-recommendation
  ports:
  - containerPort: 8085

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "recommendation_server_cert.pem"
      name: "server_cert.pem"
    - filename: "recommendation_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
