name: mongodb-rate

replicas: 1

ports:
  - port: 27020
    targetPort: 27017
 
container:
  image: mongo
  imageVersion: 5.0
  name: hotel-reserv-rate-mongo
  ports:
  - containerPort: 27017
  args:
    - "--auth" # MongoDB access control failure case

useAccessControl: true
useInitScript: true
initScriptConfigMap: mongo-rate-script