name: geo

ports:
  - port: 8083
    targetPort: 8083
 
container:
  command: /go/bin/geo
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-geo
  ports:
  - containerPort: 8083

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

useAccessControl: true

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "geo_server_cert.pem"
      name: "server_cert.pem"
    - filename: "geo_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
