name: frontend

ports:
  - port: 5000
    targetPort: 5000

container:
  command: /go/bin/frontend
  image: deathstarbench/hotel-reservation
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
