name: frontend

ports:
  - port: 5000
    targetPort: 5000

container:
  command: /go/bin/frontend
  image: saurabhjha1/hotel-reservation
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config

tlsCertificates:
  - name: ssl-certs
    mountPath: /workspace/x509
    certfiles:
    - filename: "frontend_server_cert.pem"
      name: "server_cert.pem"
    - filename: "frontend_server_key.pem"
      name: "server_key.pem"
    - filename: "ca_cert.pem"
      name: "ca_cert.pem"
